config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models

  root :to => "home#index"

  post 'home/import_list/', to: 'home#import_list'
  post 'home/create_list/', to: 'home#create_list'
  post 'home/import_list_to_db/', to: 'home#import_list_to_db'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :list
  validates :file_example, :name, :file_path, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :documents, dependent: :destroy
  belongs_to :user
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/state.rb
class State < ApplicationRecord

  def self.humanize_attr
    fields_for_select = []
    columns.map { |column| fields_for_select << {"#{column.name}": column.name.humanize} unless ['id'].include?(column.name)}
    fields_for_select
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # TODO: Need refactoring before the merge with master
  before_action :get_list, only: [:index, :import_list, :import_list_to_db, :create_list]

  def index
  end

  def import_list
    import(params[:document][:file_example])
    flash.now[:success] = "You are added file to List"
    @created_list = List.find(params[:document][:list_id])
  end

  def create_list
    params[:list][:user_id] = current_user.id
    @created_list = List.new(list_params)
    @created_list.save
    flash.now[:success] = 'List was Created'
  end

  def import_list_to_db

  end

  private

  def get_list
    @list = List.all
    @new_list = List.new
  end

  def list_params
    params.require(:list).permit(
        :list_name, :comments, :user_id
    )
  end

  def import(file)
    File.open("#{Rails.root}/public/documents/#{file.original_filename}", "wb") { |f| f.write(params[:document][:file_example].read) }
    spreadsheet = open_spreadsheet(file)
    count_row = 0
    spreadsheet.each do |row|
      count_row += row.count
    end

    body = []
    30.times() do |index|
      body << spreadsheet.row(index) if index > 1
    end
    spreadsheet = { header: spreadsheet.row(1), body: body }
    List.find_by(id: params[:document][:list_id]).documents.new(file_example: [spreadsheet].collect {|x| OpenStruct.new(x).marshal_dump }.to_json, name: file.original_filename,
                                                                               row_count: count_row, file_path: "/public/documents/#{file.original_filename}", updated_at: Time.now, created_at:Time.now).save
  end

  def open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
      notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def document_name(doc)
    doc.present? ? "#{doc.name} (#{doc.row_count})" : doc.name
  end

  def spreadsheet(doc)
    JSON.parse(doc.file_example)[0]
  end

  def mapped_fields(doc)
    JSON.parse(doc.mapped_field)
  end

  def selected_mapped_field(doc, i)
    m_f = mapped_fields(doc)[(i + 1).to_s]
    m_f.present? ? m_f : ''
  end

  def list_imported_to_db(list)
    list.documents.where(list_id: list.id, status: ['Your file is being processed', 'List successfully uploaded to DB']).count > 0
  end

  def csv_table_html_attr
    { disabled: true, include_blank: true, class: 'selectric', style: 'border:none;background:none; width: 100px;' }
  end

  def states_for_selector
    State.humanize_attr.collect{ |u| [u.values[0],  u.keys[0]]}
  end
end

app/views/home/_csv_preview.html.haml
%table{:cellspacing => "0", id: "gvMain#{doc.id}"}
  %tr.small{class: "GridViewScrollHeader"}
    %th #
    %th Our Fields
    %th Mapped Field
    - spreadsheet(doc)['body'].each_with_index do |empty_header, index|
      %td.text-bla= "Row #{index + 1}"

  %tbody
    - spreadsheet(doc)['header'].each_with_index do |header, index|
      %tr.small{class: "GridViewScrollItem#{list.id}"}
        %td="Column #{index + 1}"
        %td= header
        = form_tag home_import_list_to_db_path do
          %td
            - if list_imported_to_db(list)
              = select_tag('categories', options_for_select(states_for_selector,
                          { selected: selected_mapped_field(doc, index) }), csv_table_html_attr.each { |attr| attr} )
            - else
              = select_tag('categories', options_for_select(states_for_selector,
                          {selected: selected_mapped_field(doc, index) } ),
                          include_blank: true,  class: 'selectric', style: 'border:none;background:none; width: 100px;',
                          onchange: "UpdateSelectors(#{index + 1}, #{list.id}, this, #{list.id})")
          - spreadsheet(doc)['body'].each do |body_content|
            %td.text-bla= body_content[index]

app/views/home/_csv_table.html.haml
#accordion
  - list.documents.each do |doc|
    %div{"aria-controls" => "collapse-#{doc.id}", "aria-expanded" => "false",
        "data-target" => "#collapse-#{doc.id}",
        "data-toggle" => "collapse", onclick: "FrozeTable('gvMain#{doc.id}',
        'collapse-#{doc.id}');", id: "heading-#{doc.id}"}
      .row
        .col-md-2
        .col-md-6
          %span
            = document_name(doc)
        .col-md-4
          .small
            = doc.status
    .collapse{"aria-labelledby" => "heading-#{doc.id}", "data-parent" => "#accordion", id: "collapse-#{doc.id}"}
      .row.no-margin
        .container
          .table
            - if doc.present?
              = render 'csv_preview', doc: doc, list: list

          %span.float-left
            = render 'import_to_db_form', doc: doc, list: list

          %span.float-right.pr-5
            %i.prev.fa.fa-chevron-left.text-primary{style: 'cursor: pointer;', onclick: "ScrollLeft(#{doc.id})"}
            %i.next.fa.fa-chevron-right.text-primary{style: 'cursor: pointer;', onclick: "ScrollRight(#{doc.id})"}

app/views/home/_import_to_db_form.html.haml
- if doc.present? && doc.status == 'List not uploaded to DB'
  = form_tag home_import_list_to_db_path, remote: true do
    = hidden_field_tag(:user_id, current_user.id)
    = hidden_field_tag(:list_conquest_id, doc.id)
    = hidden_field_tag(:list_id, list.id)
    = button_tag 'Import To DB', class: 'btn btn-sm btn-primary btn-file pull-right mrgn1-left'
- else
  .text-red
    = doc.status

app/views/home/_list.html.haml
%tr.bordered-top{"data-target" => "#file-list-#{list.id}", "data-toggle" => "modal"}
  %td= list.list_name
  %td= list.comments
  %td= 'Quantity'
  %td= 'Date Posted'
  %td= 'Uploaded by	'
  %td= 'Status'
  %td
    delete btn

app/views/home/_list_table.html.haml
%table.table-hover.small{:style => "width:100%"}
  %thead
    %tr.text-blue
      %th List Name
      %th Comments
      %th Quantity
      %th Date Posted
      %th Uploaded by
      %th Status
      %th Delete List

  %tbody#list
    - if @list.present?
      - @list.each do |list|
        = render partial: 'list', locals: {list: list}
    - else
      %tr#list-empty
        %td You do not have any List

app/views/home/_modal_footer.html.haml
= form_for list.documents.new, url: home_import_list_path, id: 'import_list', remote: true do |f|
  = f.file_field :file_example, type: 'file', placehold: 'Add New File', id: 'new-file', style: 'display: none;'
  = f.label 'New File', id: 'new-file-label', for: 'new-file', class: 'btn btn-sm btn-outline-primary mb-0 pt-2'
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field(:list_id, value: list.id)
  = f.button 'Submit', class: 'btn btn-primary btn-sm', disabled: true, id: 'submit-form'

:javascript
  $(document).on('change', ':file', function() {
    if($('#new-file-label').text().length != 0)
      $('#submit-form').attr('disabled', false);
    else
      $('#submit-form').attr('disabled',true);
    })

   $("[type=file]").on("change", function(){
    var file = this.files[0].name;
    var dflt = $(this).attr("placeholder");
    if($(this).val()!=""){
      $(this).next().text(file);
    } else {
      $(this).next().text(dflt);
    }
  });

app/views/home/_model_list.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "file-list-#{list.id}", :role => "dialog", :tabindex => "-1", id: "file-list-#{list.id}"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        = flash_messages
      .modal-body
        = render 'home/csv_table', list: list

      .modal-footer.pull-left.no-border
        = render 'home/modal_footer', list: list

app/views/home/_new_form.html.haml
#uploadList.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "uploadList", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body
        = form_for @new_list, url: home_create_list_path, remote: true do |f|
          %table.table
            %thead
              %tr
                %td.border-top-0.text-blue.text-primary Create List
            %tbody
              %tr
                %td= f.text_field(:list_name, :placeholder =>"Enter List Name", class: "form-control")
              %tr
                %td= f.text_field(:comments, :placeholder =>"Enter Comments", class: "form-control")
          .p-2
            = f.submit 'Create List', class: 'button btn-sm btn-primary', data: {target: "#", toggle: "modal"}

app/views/home/create_list.js.erb
$('#list').prepend('<%= j render partial: 'home/list', locals: {list: @created_list} %>')
$('#model-list').prepend('<div id="model-list-<%= @created_list.id %>"><%= j render partial: 'home/model_list', locals: {list: @created_list} %></div>')
$('#new-form').html('<%= j render partial: 'home/new_form' %>')
$('.modal-backdrop.fade.show').hide();

$("#file-list-<%= @created_list.id %>").modal('show');

app/views/home/index.html.haml
.row
  .container-fluid
    %button.btn-sm.btn-primary{"data-target" => "#uploadList", "data-toggle" => "modal", :type => "button"}
      Add

#new-form
  = render 'new_form'

#list-table
  = render 'home/list_table'

#model-list
  - if @list.present?
    - @list.each do |list|
      %div{id: "model-list-#{list.id}"}
        = render 'home/model_list', list: list

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-sm.bg-dark.navbar-dark
  .content-center
    #navbarTogglerDemo02.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
        = link_to 'BorrowWorks', root_path, class: 'navbar-brand'
      %form.form-inline.my-2.my-lg-0
        .color-white
          - if user_signed_in?
            Logged in as
            = succeed "." do
              %strong= current_user.email
            = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BorrowWorks
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render partial: 'layouts/header'
    .container
      .container-fluid
        .content-center.pd-top-1
          = flash_messages
          %p.navbar-text.pull-right
          = yield
    #footer